# This is a basic workflow to help you get started with Actions

name: Deploy to IoT Central

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_To_Prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: pwsh
        run: .\Powershell\IoTC-Task.ps1 -ConfigPath 'Config\Production\IoTC Configuration\' -AppName iotdemo-production -ApiToken "${{ secrets.CONN_STRING }}" -ServicePrincipalPassword "${{ secrets.SP_PASSWORD }}" -AppID "${{ secrets.APPID }}" -keyvault 'IOTC-KV-AHCSA-Prod' -TenantID "${{ secrets.SP_Tenant }}"

